-- DEPRECATED — run this file in Supabase SQL Editor instead:
--   supabase/migrations/20260611_rls_role_based_security.sql
--
-- Role-based RLS (replaces open MVP + anon policies):
--   • anon (no JWT) → no table access
--   • coach → read stats; write pitches, lineups, game tracker fields
--   • analyst/admin → full stats read/write
