/**
 * Full stat names for table header `title` attributes (hover tooltips).
 * Keep in sync with batting stats columns across analyst stats / profiles.
 */

import { REGULATION_INNINGS } from "@/lib/leagueConfig";

const R = REGULATION_INNINGS;

export const BATTING_STAT_HEADER_TOOLTIPS = {
  rank: "Rank",
  player: "Player name",
  pos: "Position",
  bats: "Batting Handedness",
  gp: "Games played",
  gs: "Games started",
  pa: "Plate appearances",
  ab: "At-bats",
  h: "Hits",
  double: "Doubles",
  triple: "Triples",
  hr: "Home runs",
  rbi: "Runs batted in",
  r: "Runs scored",
  sb: "Stolen bases",
  cs: "Caught stealing",
  sbPct: "Stolen base percentage",
  bb: "Walks",
  ibb: "Intentional walks",
  hbp: "Hit by pitch",
  so: "Strikeouts",
  gidp: "Ground into double play",
  fieldersChoice: "Fielder's choice",
  e: "Fielding errors",
  pPa: "Pitches per plate appearance",
  kPct: "Strikeout percentage",
  bbPct: "Walk percentage",
  avg: "Batting average",
  obp: "On-base percentage",
  slg: "Slugging percentage",
  ops: "On-base plus slugging",
  opsPlus: "On-Base Plus Slugging Plus",
  woba: "Weighted on-base average",
  split: "Split (situation)",
  swingPct: "Swing rate: swings divided by pitches with a pitch log",
  whiffPct: "Whiff rate: swinging strikes divided by swings (when pitch log exists)",
  foulPct: "Foul rate: fouls divided by pitches with a pitch log",
  gbPct: "Ground balls divided by balls in play with batted-ball type",
  ldPct: "Line drives divided by balls in play with batted-ball type",
  fbPct: "Fly balls divided by balls in play with batted-ball type",
  iffPct: "Infield flies divided by balls in play with batted-ball type",
  plTyped: "Pitches in the log with a tagged pitch type (sample for mix / swing / whiff by type)",
  plMixFB: "Share of typed pitches classified as fastballs (incl. sinker, cutter, etc.)",
  plMixSL: "Share of typed pitches classified as sliders / sweepers",
  plMixCB: "Share of typed pitches classified as curveballs",
  plMixCH: "Share of typed pitches classified as changeups / splitters",
  plMixOT: "Share of typed pitches in other or unmapped categories",
  plSwFB: "Swing rate on logged fastballs",
  plSwSL: "Swing rate on logged sliders",
  plSwCB: "Swing rate on logged curveballs",
  plSwCH: "Swing rate on logged changeups",
  plSwOT: "Swing rate on other typed pitches",
  plWhiffFB: "Whiff rate on swings at logged fastballs",
  plWhiffSL: "Whiff rate on swings at logged sliders",
  plWhiffCB: "Whiff rate on swings at logged curveballs",
  plWhiffCH: "Whiff rate on swings at logged changeups",
  plWhiffOT: "Whiff rate on swings at other typed pitches",
} as const;

export const PITCHING_STAT_HEADER_TOOLTIPS = {
  rank: "Rank",
  player: "Player name",
  throws: "Throwing hand",
  g: "Games",
  gs: "Games started",
  ip: "Innings pitched",
  h: "Hits allowed",
  baa: "Batting average against",
  r: "Runs allowed",
  ir: "Inherited runners: runners on base when this pitcher entered (new mound appearance)",
  irs: "Inherited runners scored: runs that scored on this pitcher's PAs but were charged to another pitcher (e.g. prior reliever)",
  era: `Earned run average (earned runs per ${R} innings)`,
  er: "Earned runs",
  hr: "Home runs allowed",
  so: "Strikeouts",
  bb: "Walks",
  hbp: "Hit by pitch",
  e: "Fielding errors",
  fip: `Fielding independent pitching (scaled to ${R}-inning ERA)`,
  whip: "Walks plus hits per inning pitched",
  k7: `Strikeouts per ${R} innings`,
  bb7: `Walks per ${R} innings`,
  h7: `Hits allowed per ${R} innings`,
  hr7: `Home runs allowed per ${R} innings`,
  kPctPitch: "Strikeout rate",
  bbPctPitch: "Walk rate",
  strikePctPitch: "Strike rate",
  fpsPctPitch: "First-pitch strike rate",
  pPaPitch: "Pitches per plate appearance",
  vsLHB: "Batters who bat left-handed only",
  vsRHB: "Batters who bat right-handed only",
  swingPctPitchContact: "Swing rate by opposing batters on logged pitches",
  whiffPctPitchContact: "Whiff rate: swinging strikes divided by swings on logged pitches",
  foulPctPitchContact: "Foul rate on logged pitches",
  gbPctPitchContact: "Ground balls divided by BIP with type (allowed)",
  ldPctPitchContact: "Line drives divided by BIP with type (allowed)",
  fbPctPitchContact: "Fly balls divided by BIP with type (allowed)",
  iffPctPitchContact: "Infield flies divided by BIP with type (allowed)",
  paPitchContact: "Batters faced (plate appearances in sample)",
  plTypedPitch: "Pitches thrown with a tagged pitch type (sample for mix / swing / whiff by type)",
  plMixFBPitch: "Share of typed pitches thrown as fastballs",
  plMixSIPitch: "Share of typed pitches thrown as sinkers",
  plMixFCPitch: "Share of typed pitches thrown as cutters",
  plMixSLPitch: "Share of typed pitches thrown as sliders",
  plMixSWPitch: "Share of typed pitches thrown as sweepers",
  plMixCBPitch: "Share of typed pitches thrown as curveballs",
  plMixCHPitch: "Share of typed pitches thrown as changeups",
  plMixSPPitch: "Share of typed pitches thrown as splitters",
  plMixOTPitch: "Share of typed pitches in other or unmapped categories (thrown)",
  plSwFBPitch: "Opponent swing rate on logged fastballs",
  plSwSIPitch: "Opponent swing rate on logged sinkers",
  plSwFCPitch: "Opponent swing rate on logged cutters",
  plSwSLPitch: "Opponent swing rate on logged sliders",
  plSwSWPitch: "Opponent swing rate on logged sweepers",
  plSwCBPitch: "Opponent swing rate on logged curveballs",
  plSwCHPitch: "Opponent swing rate on logged changeups",
  plSwSPPitch: "Opponent swing rate on logged splitters",
  plSwOTPitch: "Opponent swing rate on other typed pitches",
  plWhiffFBPitch: "Whiff rate on swings at logged fastballs (pitcher view)",
  plWhiffSIPitch: "Whiff rate on swings at logged sinkers (pitcher view)",
  plWhiffFCPitch: "Whiff rate on swings at logged cutters (pitcher view)",
  plWhiffSLPitch: "Whiff rate on swings at logged sliders (pitcher view)",
  plWhiffSWPitch: "Whiff rate on swings at logged sweepers (pitcher view)",
  plWhiffCBPitch: "Whiff rate on swings at logged curveballs (pitcher view)",
  plWhiffCHPitch: "Whiff rate on swings at logged changeups (pitcher view)",
  plWhiffSPPitch: "Whiff rate on swings at logged splitters (pitcher view)",
  plWhiffOTPitch: "Whiff rate on swings at other typed pitches (pitcher view)",
  plBaaFBPitch:
    "Opponent AVG on ABs where the final logged pitch was a fastball (PA must count as AB; untyped final pitch excluded)",
  plBaaSIPitch:
    "Opponent AVG on ABs where the final logged pitch was a sinker (PA must count as AB; untyped final pitch excluded)",
  plBaaFCPitch:
    "Opponent AVG on ABs where the final logged pitch was a cutter (PA must count as AB; untyped final pitch excluded)",
  plBaaSLPitch:
    "Opponent AVG on ABs where the final logged pitch was a slider (PA must count as AB; untyped final pitch excluded)",
  plBaaSWPitch:
    "Opponent AVG on ABs where the final logged pitch was a sweeper (PA must count as AB; untyped final pitch excluded)",
  plBaaCBPitch:
    "Opponent AVG on ABs where the final logged pitch was a curveball (PA must count as AB; untyped final pitch excluded)",
  plBaaCHPitch:
    "Opponent AVG on ABs where the final logged pitch was a changeup (PA must count as AB; untyped final pitch excluded)",
  plBaaSPPitch:
    "Opponent AVG on ABs where the final logged pitch was a splitter (PA must count as AB; untyped final pitch excluded)",
  plBaaOTPitch:
    "Opponent AVG on ABs where the final logged pitch was other/unmapped (PA must count as AB; untyped final pitch excluded)",
} as const;
